name: server
version: 1.0.0
description: A new Get Server application.
environment: 
  sdk: '>=2.4.0 <3.0.0'

dependencies: 
  get_server: 1.1.1

dev_dependencies: 
  pedantic: 1.11.1
  test: 1.19.1

